SET check_function_bodies = false;
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (86, 53, 'Flour', '2 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (87, 53, 'Baking powder', '2 teaspoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (88, 53, 'Milk', '1 & 1/2 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (89, 53, 'Butter (melted)', '3 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (90, 53, 'Sugar', '1 tablespoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (91, 53, 'Egg', '1 large', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (92, 53, 'Salt', '1/2 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (93, 54, 'Romaine lettuce', '1 head', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (94, 54, 'Caesar dressing', '1/2 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (95, 54, 'Chicken breast (optional)', '1 (grilled and sliced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (96, 54, 'Parmesan cheese', '1/4 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (97, 54, 'Croutons', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (98, 55, 'Spaghetti', '12 ounces', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (99, 55, 'Parmesan cheese', '1 cup (grated)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (100, 55, 'Eggs', '2 large', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (101, 55, 'Bacon', '8 slices', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (102, 55, 'Salt', '1/2 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (103, 55, 'Black pepper', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (104, 56, 'Flour', '2 & 1/4 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (105, 56, 'Salt', '1/2 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (106, 56, 'Baking soda', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (107, 56, 'Vanilla extract', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (108, 56, 'Chocolate chips', '2 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (109, 56, 'Butter', '1 cup (softened)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (110, 56, 'Granulated sugar', '1/2 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (111, 56, 'Brown sugar', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (112, 56, 'Eggs', '2 large', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (113, 57, 'Greek yogurt', '2 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (114, 57, 'Honey', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (115, 57, 'Granola', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (116, 57, 'Fresh berries', '1 cup (mixed)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (117, 57, 'Mint leaves (optional)', 'For garnish', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (118, 58, 'Chicken breast', '2 (boneless, skinless)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (119, 58, 'Corn tortillas', '8', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (120, 58, 'Taco seasoning', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (121, 58, 'Olive oil', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (122, 58, 'Fresh cilantro', '1/4 cup (chopped)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (123, 58, 'Lime', '1 (cut into wedges)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (124, 58, 'Red onion', '1/4 cup (diced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (125, 59, 'Carrots', '3 (sliced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (126, 59, 'Beef chuck', '2 pounds (cubed)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (127, 59, 'Onion', '1 (chopped)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (128, 59, 'Beef broth', '4 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (129, 59, 'Potatoes', '3 (cubed)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (130, 59, 'Olive oil', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (131, 59, 'Bay leaf', '1', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (132, 59, 'Thyme', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (133, 59, 'Tomato paste', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (134, 59, 'Garlic', '3 cloves (minced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (135, 59, 'Salt and pepper', 'To taste', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (136, 60, 'Lemons', '6', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (137, 60, 'Ice', 'As needed', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (138, 60, 'Sugar', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (139, 60, 'Water', '6 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (140, 61, 'Bananas', '2', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (141, 61, 'Ice', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (142, 61, 'Greek yogurt', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (143, 61, 'Milk', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (144, 61, 'Honey', '1 tablespoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (145, 62, 'Flour', '1 & 3/4 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (146, 62, 'Sugar', '2 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (148, 62, 'Baking powder', '1 & 1/2 teaspoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (147, 62, 'Cocoa powder', '3/4 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (149, 62, 'Milk', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (150, 62, 'Vegetable oil', '1/2 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (151, 62, 'Vanilla extract', '2 teaspoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (152, 62, 'Salt', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (153, 62, 'Baking soda', '1 & 1/2 teaspoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (154, 62, 'Butter', '1/2 cup (softened)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (155, 62, 'Boiling water', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (156, 62, 'Eggs', '2 large', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (157, 62, 'Powdered sugar', '3 cups', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (158, 62, 'Cocoa powder (for frosting)', '1/2 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (159, 62, 'Milk (for frosting)', '1/4 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (160, 63, 'Avocado', '1 ripe', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (161, 63, 'Lemon juice', '1 teaspoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (162, 63, 'Salt', 'To taste', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (163, 63, 'Bread slices', '2', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (164, 63, 'Black pepper', 'To taste', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (165, 64, 'Strawberries', '1 cup (sliced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (166, 64, 'Mango', '1 (diced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (167, 64, 'Blueberries', '1 cup', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (168, 64, 'Kiwi', '2 (sliced)', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (169, 64, 'Mint leaves', 'For garnish', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (170, 64, 'Honey', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (171, 64, 'Lime juice', '1 tablespoon', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (172, 65, 'Bread slices', '2', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (173, 65, 'Butter', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (174, 65, 'Cheddar cheese', '2 slices', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (175, 66, 'Bread slices', '2', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (176, 66, 'Cheddar cheese', '2 slices', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (177, 66, 'Butter', '2 tablespoons', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (178, 67, 'Pumpkin puree', '2 cups', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (179, 67, 'Vegetable broth', '4 cups', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (180, 67, 'Onion', '1 (chopped)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (181, 67, 'Heavy cream', '1/2 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (182, 67, 'Nutmeg', '1/4 teaspoon', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (183, 67, 'Garlic', '2 cloves (minced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (184, 67, 'Salt and pepper', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (185, 67, 'Olive oil', '2 tablespoons', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (186, 68, 'Frozen berries', '1 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (187, 68, 'Almond milk', '1/2 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (188, 68, 'Banana', '1', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (189, 68, 'Chia seeds', '1 tablespoon', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (190, 68, 'Fresh fruit', '1/2 cup (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (191, 68, 'Granola', '1/4 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (192, 68, 'Nuts', '2 tablespoons (chopped)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (193, 69, 'Fettuccine pasta', '12 ounces', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (194, 69, 'Heavy cream', '1 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (195, 69, 'Chicken breast', '2 (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (196, 69, 'Butter', '4 tablespoons', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (197, 69, 'Parmesan cheese', '1 cup (grated)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (198, 69, 'Olive oil', '2 tablespoons', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (199, 69, 'Fresh parsley', 'For garnish', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (200, 69, 'Garlic', '2 cloves (minced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (201, 69, 'Salt and pepper', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (202, 70, 'Tomatoes', '2 (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (203, 70, 'Balsamic vinegar', '1 tablespoon', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (204, 70, 'Mozzarella cheese', '8 ounces (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (205, 70, 'Salt and pepper', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (206, 70, 'Olive oil', '2 tablespoons', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (207, 70, 'Fresh basil leaves', '1/4 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (208, 71, 'Mango', '1 (diced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (209, 71, 'Red onion', '1/4 cup (diced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (210, 71, 'Red bell pepper', '1/2 (diced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (211, 71, 'Lime juice', '1 tablespoon', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (212, 71, 'Cilantro', '1/4 cup (chopped)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (213, 71, 'Jalapeno', '1 (minced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (214, 71, 'Salt', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (225, 77, 'Vanilla ice cream', '2 cups', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (226, 77, 'Whipped cream', 'For topping', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (227, 77, 'Milk', '1 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (228, 77, 'Chocolate syrup', '1/4 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (229, 77, 'Chocolate shavings', 'For garnish', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (230, 78, 'Cooked chicken breast', '2 cups (shredded)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (231, 78, 'Lettuce', 'For serving', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (232, 78, 'Mayonnaise', '1/4 cup', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (233, 78, 'Celery', '1/2 cup (diced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (234, 78, 'Salt and pepper', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (235, 78, 'Bread slices', '4', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (236, 79, 'Carrots', '3 (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (237, 79, 'Salt and pepper', 'To taste', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (238, 79, 'Red bell pepper', '1 (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (239, 79, 'Broccoli florets', '2 cups', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (240, 79, 'Olive oil', '3 tablespoons', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (241, 79, 'Zucchini', '2 (sliced)', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (242, 79, 'Thyme', '1 teaspoon', 82);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (245, 80, 'Caesar dressing', '1/2 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (244, 80, 'Parmesan cheese', '1/4 cup (grated)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (243, 80, 'Romaine lettuce', '1 head (chopped)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (246, 80, 'Croutons', '1 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (247, 81, 'Chicken breasts', '4', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (248, 81, 'Garlic powder', '1/2 teaspoon', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (249, 81, 'Salt and pepper', 'To taste', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (250, 81, 'Spinach', '2 cups (fresh)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (251, 81, 'Olive oil', '2 tablespoons', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (252, 81, 'Ricotta cheese', '1/2 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (253, 81, 'Parmesan cheese', '1/4 cup (grated)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (254, 82, 'Greek yogurt', '2 cups', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (255, 82, 'Mixed berries', '1 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (256, 82, 'Granola', '1/2 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (257, 82, 'Honey', '2 tablespoons', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (258, 83, 'Tomatoes', '4 (diced)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (259, 83, 'Garlic', '2 cloves (minced)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (260, 83, 'Baguette', '1 (sliced)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (261, 83, 'Olive oil', '2 tablespoons', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (263, 83, 'Balsamic vinegar', '1 tablespoon', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (264, 83, 'Salt and pepper', 'To taste', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (262, 83, 'Fresh basil', '1/4 cup (chopped)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (265, 84, 'Quinoa', '1 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (266, 84, 'Cherry tomatoes', '1 cup (halved)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (267, 84, 'Red onion', '1/4 cup (diced)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (268, 84, 'Cucumber', '1 (diced)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (269, 84, 'Salt and pepper', 'To taste', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (270, 84, 'Olive oil', '1/4 cup', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (271, 84, 'Lemon juice', '2 tablespoons', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (272, 84, 'Feta cheese', '1/2 cup (crumbled)', 83);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (318, 130, 'tes', 'teas', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (340, 142, 'te', 'tes', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (342, 144, 'tes', 'tes', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (343, 145, 'dkfjdkf', 'dkjfkd', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (345, 147, 'trs', 'ts', 81);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (347, 149, 'dkfdjk', 'dkfj', 95);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (349, 151, 'toast', 'toast', 95);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (352, 154, 'toast', 'toast', 95);
INSERT INTO public.ingredients (id, recipe_id, name, quantity, user_id) VALUES (354, 156, 'test', 'test', 98);
SELECT pg_catalog.setval('public.ingredients_id_seq', 355, true);
