SET check_function_bodies = false;
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (273, 154, 'toast', 0, 95);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (275, 156, 'test', 0, 98);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (59, 53, 'In another bowl, whisk together the milk, egg, and melted butter.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (60, 53, 'Pour the wet ingredients into the dry ingredients and mix until just combined.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (61, 53, 'In a large bowl, sift together the flour, baking powder, sugar, and salt.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (62, 53, 'Heat a non-stick pan over medium heat and lightly grease it with butter or oil.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (63, 53, '"Pour 1/4 cup of batter onto the pan for each pancake. Cook until bubbles form on the surface, then flip and cook until golden brown on both sides.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (64, 54, 'Serve the salad immediately while it''s fresh and crisp.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (65, 54, 'Wash and chop the romaine lettuce into bite-sized pieces.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (66, 54, 'Sprinkle with Parmesan cheese and croutons. Add sliced grilled chicken if desired.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (67, 54, 'In a large bowl, toss the lettuce with Caesar dressing until well coated.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (68, 55, 'In a large skillet, cook the bacon until crispy. Remove and chop into small pieces.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (69, 55, 'Cook the spaghetti according to package instructions until al dente. Reserve 1/2 cup of pasta water and drain the rest.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (70, 55, 'In a bowl, whisk together the eggs, grated Parmesan cheese, and black pepper.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (71, 55, 'Return the pasta to the skillet and toss with the bacon and any rendered fat. Remove from heat, add the egg mixture, and toss quickly, adding reserved pasta water as needed to create a creamy sauce.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (72, 55, 'Serve hot with additional Parmesan cheese and black pepper.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (73, 56, 'In a bowl, whisk together flour, baking soda, and salt.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (74, 56, 'In a large bowl, beat the softened butter with brown sugar and granulated sugar until light and fluffy.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (75, 56, 'Beat in the eggs one at a time, then mix in the vanilla extract.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (76, 56, 'Drop rounded tablespoons of dough onto a baking sheet lined with parchment paper.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (77, 56, 'Gradually add the dry ingredients to the wet mixture, mixing until just combined. Fold in the chocolate chips.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (78, 56, 'Bake at 350°F (175°C) for 10-12 minutes, or until edges are golden brown. Cool on a wire rack.', 5, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (79, 57, 'Repeat the layers until all ingredients are used, ending with a topping of granola.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (80, 57, 'In a bowl, mix Greek yogurt with honey until well combined.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (81, 57, 'Garnish with mint leaves if desired and serve immediately.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (82, 57, 'In serving glasses or bowls, layer the yogurt mixture, fresh berries, and granola.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (83, 58, 'Rub the chicken breasts with taco seasoning.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (84, 58, 'Heat the corn tortillas in a dry skillet or over a flame until warm and pliable.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (85, 58, 'Place chicken strips on each tortilla and top with chopped cilantro and diced red onion.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (86, 58, 'Heat olive oil in a skillet over medium heat and cook the chicken until fully cooked and slightly charred, about 6-8 minutes per side. Slice into strips.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (87, 58, 'Serve with lime wedges for squeezing over the tacos.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (88, 59, 'In a large pot, heat olive oil over medium heat. Add the beef and brown on all sides.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (89, 59, 'Add the carrots, potatoes, onion, and garlic. Cook for a few minutes until the onions are translucent.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (90, 59, 'Stir in the beef broth, tomato paste, thyme, and bay leaf. Season with salt and pepper.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (91, 59, 'Remove the bay leaf and serve hot.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (92, 59, 'Bring to a boil, then reduce heat and simmer covered for 2 hours, or until the beef is tender.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (93, 60, 'Refrigerate until chilled. Serve over ice.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (94, 60, 'Juice the lemons to make about 1 cup of lemon juice.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (95, 60, 'In a large pitcher, combine the lemon juice and sugar. Stir until the sugar is dissolved.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (96, 60, 'Add water and stir well. Taste and adjust the sweetness if necessary.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (97, 61, 'In a blender, combine the bananas, Greek yogurt, milk, honey, and ice.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (98, 61, 'Blend until smooth and creamy.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (99, 61, 'Pour into glasses and serve immediately.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (100, 61, 'Peel and slice the bananas.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (101, 62, 'In a large bowl, stir together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (102, 62, 'Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round baking pans.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (103, 62, 'Stir in the boiling water (batter will be thin). Pour batter into prepared pans.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (104, 62, 'Bake for 30 to 35 minutes, or until a toothpick inserted into the center comes out clean. Cool in pans for 10 minutes, then remove to wire racks to cool completely.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (105, 62, 'For the frosting: In a medium bowl, beat the butter until creamy. Gradually add the powdered sugar and cocoa powder, alternating with milk, until smooth and spreadable.', 5, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (106, 62, 'Frost the cooled cakes and serve.', 6, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (107, 62, 'Add the eggs, milk, oil, and vanilla extract. Beat on medium speed for 2 minutes.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (108, 63, 'Cut the avocado in half, remove the pit, and scoop out the flesh into a bowl.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (109, 63, 'Spread the mashed avocado onto the toasted bread and serve immediately.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (110, 63, 'Mash the avocado with a fork and add lemon juice, salt, and pepper to taste.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (111, 63, 'Toast the bread slices until golden brown.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (112, 64, 'In a large bowl, combine the strawberries, blueberries, mango, and kiwi.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (113, 64, 'In a small bowl, whisk together the honey and lime juice.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (114, 64, 'Garnish with mint leaves and serve chilled.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (115, 64, 'Pour the honey-lime dressing over the fruit and toss gently to combine.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (116, 65, 'Place one slice of bread, buttered side down, in a skillet over medium heat.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (117, 65, 'Add the cheddar cheese slices and top with the other bread slice, buttered side up.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (118, 65, 'Butter one side of each bread slice.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (119, 65, 'Cook until the bread is golden brown and the cheese is melted, about 2-3 minutes per side.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (120, 65, 'erve hot with a side of tomato soup if desired.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (121, 66, 'Butter one side of each bread slice.', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (122, 66, 'Add the cheddar cheese slices and top with the other bread slice, buttered side up.', 2, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (123, 66, 'Place one slice of bread, buttered side down, in a skillet over medium heat.', 1, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (124, 66, 'Serve hot with a side of tomato soup if desired.', 4, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (125, 66, 'Cook until the bread is golden brown and the cheese is melted, about 2-3 minutes per side.', 3, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (126, 67, 'In a large pot, heat olive oil over medium heat. Add the chopped onion and minced garlic and cook until softened.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (127, 67, 'Stir in the pumpkin puree and vegetable broth. Bring to a boil, then reduce heat and simmer for 20 minutes.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (128, 67, 'Use an immersion blender to puree the soup until smooth.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (129, 67, 'Serve hot with a sprinkle of nutmeg on top.', 4, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (130, 67, 'Stir in the heavy cream, nutmeg, salt, and pepper. Simmer for an additional 5 minutes.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (131, 68, 'In a blender, combine the frozen berries, banana, and almond milk. Blend until smooth.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (132, 68, 'Pour the smoothie into a bowl.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (133, 68, 'Top with granola, fresh fruit, chia seeds, and nuts.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (134, 68, 'erve immediately and enjoy with a spoon." ', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (135, 69, 'In a skillet, heat olive oil over medium heat. Cook the sliced chicken until golden brown and cooked through. Remove and set aside.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (136, 69, 'Cook the fettuccine pasta according to package instructions until al dente. Drain and set aside.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (137, 69, 'Stir in the heavy cream and bring to a simmer. Add the grated Parmesan cheese and stir until melted and smooth.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (138, 69, 'Return the cooked chicken to the skillet and toss with the Alfredo sauce.', 4, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (139, 69, 'In the same skillet, melt the butter and add the minced garlic. Cook for 1 minute until fragrant.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (140, 69, 'Add the cooked fettuccine to the skillet and toss to coat in the sauce. Season with salt and pepper.', 5, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (141, 69, 'Garnish with fresh parsley and serve hot.', 6, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (142, 70, 'Tuck fresh basil leaves between the tomato and mozzarella slices.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (143, 70, 'Arrange the tomato slices and mozzarella slices alternately on a serving platter.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (144, 70, 'Drizzle with olive oil and balsamic vinegar.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (145, 70, 'Season with salt and pepper to taste. Serve immediately.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (146, 71, 'In a bowl, combine the diced mango, red bell pepper, red onion, and minced jalapeno.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (147, 71, 'Stir in the chopped cilantro and lime juice.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (148, 71, 'Season with salt to taste and mix well.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (149, 71, 'Serve the salsa with tortilla chips or as a topping for grilled chicken or fish.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (268, 149, 'teat', 0, 95);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (160, 77, 'Top with whipped cream and garnish with chocolate shavings. Serve immediately.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (161, 77, 'Pour the milkshake into glasses.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (162, 77, 'In a blender, combine the vanilla ice cream, milk, and chocolate syrup.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (163, 77, 'Blend until smooth and creamy.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (164, 78, 'Spread the chicken salad onto two slices of bread.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (165, 78, 'Top with lettuce and the remaining bread slices.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (166, 78, 'In a bowl, combine the shredded chicken, diced celery, and mayonnaise. Season with salt and pepper to taste.', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (167, 78, 'Cut the sandwiches in half and serve.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (168, 79, 'Preheat the oven to 425°F (220°C).', 0, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (169, 79, 'In a large bowl, toss the sliced carrots, zucchini, red bell pepper, and broccoli florets with olive oil, thyme, salt, and pepper.', 1, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (170, 79, 'Spread the vegetables in a single layer on a baking sheet.', 2, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (171, 79, 'Roast in the preheated oven for 20-25 minutes, or until the vegetables are tender and slightly browned.', 3, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (172, 79, 'Serve hot as a side dish.', 4, 82);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (174, 80, 'Add the Caesar dressing and toss to coat evenly.', 1, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (173, 80, 'In a large bowl, combine the chopped romaine lettuce, croutons, and grated Parmesan cheese.', 0, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (175, 80, 'Serve immediately.', 2, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (176, 81, 'Preheat the oven to 375°F (190°C).', 0, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (177, 81, 'In a bowl, combine the spinach, ricotta cheese, Parmesan cheese, garlic powder, salt, and pepper.', 1, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (178, 81, 'Cut a pocket into each chicken breast and stuff with the spinach mixture.', 2, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (179, 81, 'Heat olive oil in a skillet over medium-high heat. Sear the stuffed chicken breasts for 2-3 minutes on each side until golden brown.', 3, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (180, 81, 'Transfer the chicken to a baking dish and bake in the preheated oven for 20-25 minutes, or until the chicken is cooked through.', 4, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (181, 81, 'Serve hot with your choice of side.', 5, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (182, 82, 'Repeat the layers and serve immediately.', 2, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (183, 82, 'In a glass or bowl, layer Greek yogurt, mixed berries, and granola.', 0, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (184, 82, 'Drizzle with honey.', 1, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (185, 83, 'Preheat the oven to 400°F (200°C).', 0, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (186, 83, 'In a bowl, combine the diced tomatoes, chopped basil, minced garlic, olive oil, balsamic vinegar, salt, and pepper.', 1, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (187, 83, 'Arrange the baguette slices on a baking sheet and toast in the preheated oven for 5-7 minutes until golden brown.', 2, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (270, 151, 'toast', 0, 95);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (188, 83, 'Top each toasted baguette slice with the tomato basil mixture and serve immediately.', 3, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (189, 84, 'In a large bowl, combine the cooked quinoa, diced cucumber, halved cherry tomatoes, diced red onion, and crumbled feta cheese.', 1, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (190, 84, 'Cook the quinoa according to package instructions and let it cool.', 0, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (191, 84, 'In a small bowl, whisk together the olive oil, lemon juice, salt, and pepper.', 2, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (192, 84, 'Pour the dressing over the quinoa salad and toss to coat.', 3, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (193, 84, 'Serve chilled or at room temperature.', 4, 83);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (239, 130, 'tes', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (261, 142, 'ts', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (263, 144, 'tes', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (264, 145, 'dfkjdkfj', 0, 81);
INSERT INTO public.steps (id, recipe_id, description, step_order, user_id) VALUES (266, 147, 'test', 0, 81);
SELECT pg_catalog.setval('public.steps_id_seq', 276, true);
