-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE ingredients (
--     id SERIAL PRIMARY KEY,
--     recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE,
--     name VARCHAR(100) NOT NULL,
--     quantity VARCHAR(50) NOT NULL
-- );
