-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE ingredients
-- ADD COLUMN name_quantity VARCHAR(150) GENERATED ALWAYS AS (name || ' - ' || quantity) STORED;
